[package]
name = "christmas-carol-lyrics"
version = "0.1.0"
authors = ["nginx-x <admin@folderfile.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
